# Generated by Django 5.0.2 on 2024-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.EmailField(max_length=100)),
                ('avatar', models.ImageField(upload_to='images')),
                ('language', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
